

CREATE DATABASE advanced_lab;


CREATE TABLE employees (
    emp_id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name  varchar(50) NOT NULL,
    last_name   varchar(50) NOT NULL,
    department  varchar(100) DEFAULT 'Unassigned',
    salary      integer DEFAULT 50000,
    hire_date   date,
    status      varchar(30) DEFAULT 'Active'
);

CREATE TABLE departments (
    dept_id     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dept_name   varchar(100) NOT NULL,
    budget      integer,
    manager_id  integer
);

CREATE TABLE projects (
    project_id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_name varchar(150) NOT NULL,
    dept_id      integer,
    start_date   date,
    end_date     date,
    budget       integer
);


INSERT INTO employees
    (first_name, last_name, department, salary, hire_date, status)
VALUES
    ('Alice', 'Johnson', 'IT',       85000, '2019-03-15', 'Active'),
    ('Bob',   'Smith',   'Sales',   65000, '2021-07-10', 'Active'),
    ('Carol', 'Brown',   'HR',      45000, '2018-11-20', 'Active'),
    ('David', 'Wilson',  'Finance', 95000, '2017-01-12', 'Inactive'),
    ('Eva',   'Davis',   'IT',      70000, '2020-05-01', 'Active'),
    ('Frank', 'Miller',  'Sales',   38000, '2024-02-15', 'Terminated'),
    ('Grace', 'Taylor',  NULL,      NULL,  '2024-03-01', 'Active'),
    ('Henry', 'Moore',   'IT',      55000, '2022-08-19', 'Active');

INSERT INTO departments (dept_name, budget, manager_id)
VALUES
    ('IT',       120000, 1),
    ('Sales',     90000, 2),
    ('HR',        70000, 3);

INSERT INTO projects
    (project_name, dept_id, start_date, end_date, budget)
VALUES
    ('Cloud Migration', 1, '2022-01-01', '2022-12-01', 80000),
    ('Sales Portal',    2, '2022-04-01', '2022-11-15', 45000),
    ('HR System',       3, '2021-01-01', '2022-01-01', 60000);


INSERT INTO employees
    (emp_id, first_name, last_name, department)
VALUES
    (100, 'John', 'Anderson', 'IT');

INSERT INTO employees
    (first_name, last_name, department, salary, status)
VALUES
    ('Jane', 'Anderson', 'HR', DEFAULT, DEFAULT);

INSERT INTO departments
    (dept_name, budget, manager_id)
VALUES
    ('Marketing', 60000, NULL),
    ('Research',  110000, NULL),
    ('Support',   50000, NULL);

INSERT INTO employees
    (first_name, last_name, department, salary, hire_date)
VALUES
    ('Kevin', 'Lee', 'Finance', 50000 * 1.1, CURRENT_DATE);

CREATE TEMP TABLE temp_employees (
    emp_id      integer,
    first_name  varchar(50),
    last_name   varchar(50),
    department  varchar(100),
    salary      integer,
    hire_date   date,
    status      varchar(30)
);

INSERT INTO temp_employees
    (emp_id, first_name, last_name, department, salary, hire_date, status)
SELECT
    emp_id, first_name, last_name, department, salary, hire_date, status
FROM employees
WHERE department = 'IT';


UPDATE employees
SET salary = salary * 1.10;

UPDATE employees
SET status = 'Senior'
WHERE salary > 60000
  AND hire_date < DATE '2020-01-01';

UPDATE employees
SET department =
    CASE
        WHEN salary > 80000 THEN 'Management'
        WHEN salary BETWEEN 50000 AND 80000 THEN 'Senior'
        ELSE 'Junior'
    END;

UPDATE employees
SET department = DEFAULT
WHERE status = 'Inactive';

UPDATE departments AS d
SET budget = (
    SELECT ROUND(AVG(e.salary) * 1.20)::integer
    FROM employees AS e
    WHERE e.department = d.dept_name
)
WHERE EXISTS (
    SELECT 1
    FROM employees AS e
    WHERE e.department = d.dept_name
);

UPDATE employees
SET salary = salary * 1.15,
    status = 'Promoted'
WHERE department = 'Sales';


DELETE FROM employees
WHERE status = 'Terminated';

DELETE FROM employees
WHERE salary < 40000
  AND hire_date > DATE '2023-01-01'
  AND department IS NULL;

DELETE FROM departments AS d
WHERE d.dept_id NOT IN (
    SELECT DISTINCT d2.dept_id
    FROM departments AS d2
    JOIN employees AS e
      ON e.department = d2.dept_name
    WHERE e.department IS NOT NULL
);

DELETE FROM projects
WHERE end_date < DATE '2023-01-01'
RETURNING *;


INSERT INTO employees
    (first_name, last_name, salary, department)
VALUES
    ('Liam', 'Clark', NULL, NULL);

UPDATE employees
SET department = 'Unassigned'
WHERE department IS NULL;

DELETE FROM employees
WHERE salary IS NULL
   OR department IS NULL;


INSERT INTO employees
    (first_name, last_name, department, salary, hire_date)
VALUES
    ('Mia', 'Walker', 'IT', 72000, CURRENT_DATE)
RETURNING
    emp_id,
    first_name || ' ' || last_name AS full_name;

WITH old_salaries AS (
    SELECT emp_id, salary AS old_salary
    FROM employees
    WHERE department = 'IT'
)
UPDATE employees AS e
SET salary = e.salary + 5000
FROM old_salaries AS o
WHERE e.emp_id = o.emp_id
RETURNING
    e.emp_id,
    o.old_salary,
    e.salary AS new_salary;


DELETE FROM employees
WHERE hire_date < DATE '2020-01-01'
RETURNING *;


INSERT INTO employees
    (first_name, last_name, department, salary, hire_date)
SELECT
    'Noah', 'Harris', 'IT', 68000, CURRENT_DATE
WHERE NOT EXISTS (
    SELECT 1
    FROM employees
    WHERE first_name = 'Noah'
      AND last_name = 'Harris'
);

UPDATE employees AS e
SET salary = e.salary * (
    CASE
        WHEN (
            SELECT d.budget
            FROM departments AS d
            WHERE d.dept_name = e.department
        ) > 100000
        THEN 1.10
        ELSE 1.05
    END
)
WHERE EXISTS (
    SELECT 1
    FROM departments AS d
    WHERE d.dept_name = e.department
);

INSERT INTO employees
    (first_name, last_name, department, salary, hire_date)
VALUES
    ('Olivia', 'Martin', 'IT',      60000, CURRENT_DATE),
    ('Peter',  'Thompson', 'Sales', 55000, CURRENT_DATE),
    ('Quinn',  'Garcia', 'HR',     48000, CURRENT_DATE),
    ('Ruby',   'Martinez', 'IT',   62000, CURRENT_DATE),
    ('Sam',    'Robinson', 'Sales', 58000, CURRENT_DATE);

UPDATE employees
SET salary = salary * 1.10
WHERE first_name IN ('Olivia', 'Peter', 'Quinn', 'Ruby', 'Sam')
  AND last_name IN ('Martin', 'Thompson', 'Garcia', 'Martinez', 'Robinson')
  AND hire_date = CURRENT_DATE;

CREATE TABLE IF NOT EXISTS employee_archive (
    LIKE employees INCLUDING ALL
);

WITH moved AS (
    DELETE FROM employees
    WHERE status = 'Inactive'
    RETURNING *
)
INSERT INTO employee_archive
SELECT *
FROM moved;

UPDATE projects AS p
SET end_date = p.end_date + INTERVAL '30 days'
WHERE p.budget > 50000
  AND (
      SELECT COUNT(*)
      FROM employees AS e
      JOIN departments AS d
        ON e.department = d.dept_name
      WHERE d.dept_id = p.dept_id
  ) > 3;